name: aix-doc@v0
description: "Generate professional code documentation on every commit."
author: Ben Matanda
outputs:
  time:
    description: 'Generate professional code documentation on every commit'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: 'blue'
  icon: 'file-minus'
